version: "3.9"

services:
  pg_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=wallet_service_db
      - POSTGRES_USER=Merdan
      - POSTGRES_PASSWORD=353062
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5415:5432"

volumes:
  db: