version: "3.1"

services:
  postgres:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    container_name: 'java-postgres'
    environment:
      - POSTGRES_DB=appartmants_db
      - POSTGRES_USER=Merdan
      - POSTGRES_PASSWORD=353062

  app:
      build: ./
      container_name: 'java-app'
      ports:
        - "8080:8080"




