database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5415/wallet_service_db
  username: Merdan
  password: 353062
  changeLogLog: liquibase/changelog.xml
  liquibaseSchema: migration